import './components/calendar/calendar'
import './components/dropdown/dropdown'
import './components/range-slider/range-slider'
import './components/checkbox-list/checkbox-list'

import './pages/colors-type/colors-type'
import './pages/form-elements/form-elements'
import './pages/cards/cards'
import './pages/headers-footers/headers-footers'
import './pages/landing-page/landing-page'
import './pages/search-room/search-room'
import './pages/room-details/room-details'
import './pages/registration/registration'
import './pages/sign-in/sign-in'

import './scss/vars.scss'
import './scss/mixin.scss'